name: CMake

on:
  push:
    tags:
        - v*
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Get submodules
      run: git submodule update --init

    - name: Install deps
      # Install all the deps we need to actually build this
      run: sudo apt-get update && sudo apt-get install -y gcc-arm-none-eabi python3-pyelftools

    - name: Build
      # Build your program with the given configuration
      run: ${{github.workspace}}/build.sh

    - uses: actions/upload-artifact@v3
      with:
        name: Release Artifacts
        path: release/

  release:
    name: Release pushed tag
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - name: Get build artifacts
        uses: actions/download-artifact@v3
        with:
          name: Release Artifacts
          path: release/
      - name: Tar release
        run: tar czf release.tgz release/
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${GITHUB_REPOSITORY#*/} ${tag#v}" \
              --generate-notes release.tgz
